### ISSUE TITLE
https://thepiratebay.org访问不了？

### ISSUE THREAD

**Issue by CharleVV** [bitdust/Douban2Piratebay#1]
更换为https://thepiratebay.cd正常了

**Comment by bitdust** [comment]
thepiratebay.org 是官方站，可能需要翻墙

**Comment by ghost** [comment]
可以到海盗湾贴吧里找下，有镜像站，可以使用。
不过，我是想建议下，可以直接搜索电影的英文名字么，感觉搜那个编号，不如搜英文名字出来的结果丰富。

**Comment by bitdust** [comment]
@LarT2P 
默认还是会用org主站的，毕竟更稳定。但是我会在里面提供几个备选镜像站，可以手动设置。
另外imdb编号还是搜索比较准确，而且对非英语电影支持相对更好。
